// import {
//     UserRole,
//     UserStatus,
//     EquipmentStatus,
//     EquipmentCondition,
//     EquipmentCategory,
//     InventoryItemStatus,
//     InventoryTransactionType,
//     MaintenanceType,
//     MaintenanceStatus,
//     Location,
//     User,
//     Equipment,
//     InventoryItem,
//     InventoryTransaction,
//     MaintenanceRecord,
//     Document,
//   } from '../models/types';


//   // Mock users data
//   export const users: User[] = [
//     {
//       id: 'user1',
//       name: 'Cheikh Diop',
//       email: 'cheikh.diop@example.com',
//       password: "kkkkkkkkkkkkkkk",
//       role: UserRole.ADMIN,
//       status: UserStatus.ACTIVE,
//       avatar: '/img/users/cheikh.jpg',
//       organization: 'SmartOp360',
//       phoneNumber: '+221 77 123 45 67',
//       jobTitle: 'Administrateur',
//       department: 'IT',
//       createdAt: new Date('2022-01-15T10:00:00.000Z'),
//       lastLogin: new Date('2023-10-25T14:30:00.000Z'),
//       updatedAt: new Date('2023-10-25T14:30:00.000Z')
//     },
//     {
//       id: 'user2',
//       name: 'Awa Ndiaye',
//       email: 'awa.ndiaye@example.com',
//       password: "kkkkkkkkkkkkkkk",

//       role: UserRole.PROJECT_MANAGER,
//       status: UserStatus.ACTIVE,
//       avatar: '/img/users/awa.jpg',
//       organization: 'SmartOp360',
//       phoneNumber: '+221 77 234 56 78',
//       jobTitle: 'Chef de Projet',
//       department: 'Gestion de Projet',
//       createdAt: new Date('2022-02-20T11:00:00.000Z'),
//       lastLogin: new Date('2023-10-24T13:45:00.000Z'),
//       updatedAt: new Date('2023-10-24T13:45:00.000Z')
//     },
//     {
//       id: 'user3',
//       name: 'Mamadou Diallo',
//       email: 'mamadou.diallo@example.com',
//       password: "kkkkkkkkkkkkkkk",

//       role: UserRole.TECHNICIAN,
//       status: UserStatus.ACTIVE,
//       avatar: '/img/users/mamadou.jpg',
//       organization: 'SmartOp360',
//       phoneNumber: '+221 77 345 67 89',
//       jobTitle: 'Technicien',
//       department: 'Maintenance',
//       createdAt: new Date('2022-03-10T09:00:00.000Z'),
//       lastLogin: new Date('2023-10-23T16:20:00.000Z'),
//       updatedAt: new Date('2023-10-23T16:20:00.000Z')
//     },
//     {
//       id: 'user4',
//       name: 'Fatou Sow',
//       email: 'fatou.sow@example.com',
//       password: "kkkkkkkkkkkkkkk",
//       role: UserRole.CONTRACTOR,
//       status: UserStatus.ACTIVE,
//       avatar: '/img/users/fatou.jpg',
//       organization: 'TechElec SARL',
//       phoneNumber: '+221 77 456 78 90',
//       jobTitle: 'Contractor',
//       department: 'Operations',
//       createdAt: new Date('2022-04-05T12:00:00.000Z'),
//       lastLogin: new Date('2023-10-22T15:10:00.000Z'),
//       updatedAt: new Date('2023-10-22T15:10:00.000Z')
//     }
//   ];
  
//   // Locations for inventory
//   export const inventoryLocations: { [key: string]: Location } = {
//     mainWarehouse: {
//       id: 'loc1',
//       latitude: 14.7167,
//       longitude: -17.4677,
//       address: 'Zone Industrielle',
//       city: 'Dakar',
//       region: 'Dakar',
//       country: 'Sénégal',
//       description: 'Entrepôt principal'
//     },
//     secondaryWarehouse: {
//       id: 'loc2',
//       latitude: 14.7389,
//       longitude: -17.4572,
//       address: 'Technopole',
//       city: 'Dakar',
//       region: 'Dakar',
//       country: 'Sénégal',
//       description: 'Entrepôt secondaire'
//     },
//     thiesOffice: {
//       id: 'loc3',
//       latitude: 14.7910,
//       longitude: -16.9359,
//       address: 'Zone industrielle',
//       city: 'Thiès',
//       region: 'Thiès',
//       country: 'Sénégal',
//       description: 'Bureau régional de Thiès'
//     },
//     fatickSite: {
//       id: 'loc4',
//       latitude: 14.3390,
//       longitude: -16.4110,
//       address: 'Route Nationale',
//       city: 'Fatick',
//       region: 'Fatick',
//       country: 'Sénégal',
//       description: 'Site de projet Fatick'
//     }
//   };
  
//   // Mock equipment data
//   export const equipments: Equipment[] = [
//     // … tes deux premiers objets, inchangés …
  
//     // equipment3 corrigé
//     {
//       id: 'equipment3',
//       name: 'Testeur haute tension',
//       type: 'Équipement de mesure',
//       model: 'HVT-5000Pro',
//       serialNumber: 'HVT-2023-03-045',
//       manufacturer: 'SafeTest Electronics',
//       purchaseDate: new Date('2023-03-18T00:00:00.000Z'),      // ← Date, pas string
//       purchasePrice: 4800000,
//       currency: 'XOF',
//       warrantyExpirationDate: new Date('2025-03-18T00:00:00.000Z'),
//       status: EquipmentStatus.AVAILABLE,
//       condition: EquipmentCondition.EXCELLENT,
//       location: inventoryLocations.mainWarehouse,             // Location complet
//       description: 'Testeur haute tension pour vérification des installations électriques',
//       specifications: {
//         'tension max': '5000V',
//         'précision': '±0.5%',
//         'modes': 'AC/DC',
//         'résistance isolation': "jusqu'à 10 TΩ",
//         'interface': 'numérique'
//       },
//       category: EquipmentCategory.MEASUREMENT,
//       tags: [],                                               // ← Obligatoire
//       lastMaintenance: new Date('2023-07-10T00:00:00.000Z'),
//       nextMaintenance: new Date('2024-01-10T00:00:00.000Z'),
//       createdAt: new Date('2023-03-18T11:20:00.000Z'),
//       updatedAt: new Date('2023-07-10T16:45:00.000Z'),
//       barcode: 'EQ-TST-001',
//       qrCode: 'https://qr.smartop360.com/equipment/equipment3',
//       maintenanceHistory: [],                                 // ← Obligatoire
//       documents: []                                           // ← Obligatoire
//     },
  
//     // equipment4 corrigé
//     {
//       id: 'equipment4',
//       name: 'Groupe électrogène 100kVA',
//       type: 'Alimentation secours',
//       model: 'PowerGen 100D',
//       serialNumber: 'GRP-2022-08-076',
//       manufacturer: 'EnergySolutions',
//       purchaseDate: new Date('2022-08-25T00:00:00.000Z'),
//       purchasePrice: 15000000,
//       currency: 'XOF',
//       warrantyExpirationDate: new Date('2024-08-25T00:00:00.000Z'),
//       status: EquipmentStatus.IN_USE,
//       condition: EquipmentCondition.GOOD,
//       location: inventoryLocations.thiesOffice,
//       description: 'Groupe électrogène diesel pour alimentation de secours',
//       specifications: {
//         'puissance': '100 kVA',
//         'tension': '400V triphasé',
//         'moteur': 'Diesel 6 cylindres',
//         'réservoir': '200L',
//         'autonomie': '12h à pleine charge',
//         'niveau sonore': '72 dB'
//       },
//       category: EquipmentCategory.POWER,
//       tags: [],                                               // ← Obligatoire
//       lastMaintenance: new Date('2023-05-05T00:00:00.000Z'),
//       nextMaintenance: new Date('2023-11-05T00:00:00.000Z'),
//       createdAt: new Date('2022-08-25T14:10:00.000Z'),
//       updatedAt: new Date('2023-05-05T10:30:00.000Z'),
//       barcode: 'EQ-GEN-001',
//       qrCode: 'https://qr.smartop360.com/equipment/equipment4',
//       maintenanceHistory: [],                                 // ← Obligatoire
//       documents: []                                           // ← Obligatoire
//     },
//     {
//         id: 'equipment5',
//         name: 'Drone d\'inspection DJI Mavic 3',
//         type: 'Drone',
//         model: 'Mavic 3 Pro',
//         serialNumber: 'DJM3-2023-01-128',
//         manufacturer: 'DJI',
//         purchaseDate: new Date('2024-08-25T00:00:00.000Z'),
//         purchasePrice: 1800000,
//         currency: 'XOF',
//         warrantyExpirationDate: new Date('2024-08-25T00:00:00.000Z'),
//         status: EquipmentStatus.MAINTENANCE,
//         condition: EquipmentCondition.FAIR,
//         location: inventoryLocations.mainWarehouse,
//         description: 'Drone professionnel pour inspection des lignes électriques et infrastructures',
//         specifications: {
//           'caméra': 'Hasselblad 20MP',
//           'zoom': '28x hybride',
//           'autonomie': '46 minutes',
//           'portée': '15km',
//           'vitesse max': '75km/h',
//           'résistance vent': '12m/s'
//         },
//         category: EquipmentCategory.ELECTRONIC,
//         tags: ['drone', 'inspection', 'aérien'],
//         lastMaintenance: new Date('2023-05-05T00:00:00.000Z'),
//         nextMaintenance:  new Date('2023-10-05T00:00:00.000Z'),
//         createdAt: new Date('2022-04-05T12:00:00.000Z'),
//         updatedAt: new Date('2022-04-05T12:00:00.000Z'),
//         barcode: 'EQ-DRN-001',
//         qrCode: 'https://qr.smartop360.com/equipment/equipment5',
//         maintenanceHistory: [],                                 // ← Obligatoire
//         documents: []   
//       },
//       {
//         id: 'equipment6',
//         name: 'Poste à souder',
//         type: 'Équipement de soudure',
//         model: 'WeldTech 250i',
//         serialNumber: 'WLD-2022-11-092',
//         manufacturer: 'TechWeld',
//         purchaseDate: new Date('2022-11-15T00:00:00.000Z'),
//         purchasePrice: 750000,
//         currency: 'XOF',
//         warrantyExpirationDate: new Date('2024-11-15T00:00:00.000Z'),
//         status: EquipmentStatus.AVAILABLE,
//         condition: EquipmentCondition.GOOD,
//         location: inventoryLocations.secondaryWarehouse,
//         description: 'Poste à souder inverter pour soudure professionnelle',
//         specifications: {
//           'intensité max': '250A',
//           'alimentation': '230V',
//           'procédés': 'MMA/TIG/MIG',
//           'épaisseur max': '10mm',
//           'poids': '12kg'
//         },
//         category: EquipmentCategory.MECHANICAL,
//         tags: ['soudure', 'inverter', 'atelier'],
//         lastMaintenance: new Date('2023-06-20T00:00:00.000Z'),
//         nextMaintenance: new Date('2023-12-20T00:00:00.000Z'),
//         createdAt: new Date('2022-11-15T15:30:00.000Z'),
//         updatedAt: new Date('2023-06-20T11:15:00.000Z'),
//         barcode: 'EQ-SOU-001',
//         qrCode: 'https://qr.smartop360.com/equipment/equipment6',
//         maintenanceHistory: [],
//         documents: []
//       },
//       {
//         id: 'equipment7',
//         name: 'Ordinateur portable',
//         type: 'Équipement informatique',
//         model: 'ThinkPad X1 Carbon',
//         serialNumber: 'LNV-2023-04-153',
//         manufacturer: 'Lenovo',
//         purchaseDate: new Date('2023-04-05T00:00:00.000Z'),
//         purchasePrice: 1200000,
//         currency: 'XOF',
//         warrantyExpirationDate: new Date('2026-04-05T00:00:00.000Z'),
//         status: EquipmentStatus.IN_USE,
//         condition: EquipmentCondition.NEW,
//         assignedTo: users[1],
//         location: inventoryLocations.mainWarehouse,
//         description: 'Ordinateur portable professionnel pour ingénieurs',
//         specifications: {
//           'processeur': 'Intel Core i7-1270P',
//           'mémoire': '32GB DDR5',
//           'stockage': 'SSD 1TB',
//           'écran': '14" WUXGA',
//           'système': 'Windows 11 Pro',
//           'batterie': '15h'
//         },
//         category: EquipmentCategory.IT,
//         tags: ['informatique', 'ordinateur', 'portable'],
//         lastMaintenance: new Date('2023-07-15T00:00:00.000Z'),
//         nextMaintenance: new Date('2024-01-15T00:00:00.000Z'),
//         createdAt: new Date('2023-04-05T08:55:00.000Z'),
//         updatedAt: new Date('2023-07-15T16:40:00.000Z'),
//         barcode: 'EQ-IT-001',
//         qrCode: 'https://qr.smartop360.com/equipment/equipment7',
//         maintenanceHistory: [],
//         documents: []
//       },
//       {
//         id: 'equipment8',
//         name: 'Dérouleuse de câble',
//         type: 'Équipement de chantier',
//         model: 'CableMax 500',
//         serialNumber: 'DCB-2022-09-063',
//         manufacturer: 'LineTech',
//         purchaseDate: new Date('2022-09-18T00:00:00.000Z'),
//         purchasePrice: 3200000,
//         currency: 'XOF',
//         warrantyExpirationDate: new Date('2024-09-18T00:00:00.000Z'),
//         status: EquipmentStatus.REPAIR,
//         condition: EquipmentCondition.FAIR,
//         location: inventoryLocations.secondaryWarehouse,
//         description: 'Dérouleuse hydraulique de câbles pour installation de lignes électriques',
//         specifications: {
//           'charge max': '500kg',
//           'diamètre bobine': '1.6m',
//           'vitesse': '0-40m/min',
//           'moteur': 'Hydraulique',
//           'contrôle': 'Manuel/Automatique'
//         },
//         category: EquipmentCategory.CONSTRUCTION,
//         tags: ['câble', 'dérouleuse', 'chantier'],
//         lastMaintenance: new Date('2023-05-12T00:00:00.000Z'),
//         nextMaintenance: new Date('2023-11-12T00:00:00.000Z'),
//         maintenanceHistory: [
//             {
//               id: 'maint1',
//               equipmentId: 'equipment8',
//               maintenanceType: MaintenanceType.CORRECTIVE,
//               date: new Date('2023-08-20T00:00:00.000Z'),
//               description: 'Remplacement du système hydraulique défectueux',
//               technician: users[3],
//               technicianId: users[3].id, // à ajouter
//               cost: 350000,
//               currency: 'XOF',
//               status: MaintenanceStatus.IN_PROGRESS,
//               notes: 'Pièce en commande, délai 10 jours',
//               scheduledDate: new Date('2023-08-15T00:00:00.000Z'),
//               createdBy: users[2],
//               createdById: users[2].id, // à ajouter
//               createdAt: new Date('2023-08-15T09:30:00.000Z'),
//               updatedAt: new Date('2023-08-20T14:15:00.000Z'),
//               equipment: {
//                 id: 'equipment8',
//                 name: 'Dérouleuse de câble',
//                 type: 'Équipement de chantier',
//                 model: 'CableMax 500',
//                 serialNumber: 'DCB-2022-09-063',
//                 manufacturer: 'LineTech',
//                 purchaseDate: new Date('2022-09-18T00:00:00.000Z'),
//                 purchasePrice: 3200000,
//                 currency: 'XOF',
//                 warrantyExpirationDate: new Date('2024-09-18T00:00:00.000Z'),
//                 status: EquipmentStatus.REPAIR,
//                 condition: EquipmentCondition.FAIR,
//                 location: inventoryLocations.secondaryWarehouse,
//                 description: 'Dérouleuse hydraulique de câbles pour installation de lignes électriques',
//                 specifications: {
//                   'charge max': '500kg',
//                   'diamètre bobine': '1.6m',
//                   'vitesse': '0-40m/min',
//                   'moteur': 'Hydraulique',
//                   'contrôle': 'Manuel/Automatique'
//                 },
//                 category: EquipmentCategory.CONSTRUCTION,
//                 tags: ['câble', 'dérouleuse', 'chantier'],
//                 lastMaintenance: new Date('2023-05-12T00:00:00.000Z'),
//                 nextMaintenance: new Date('2023-11-12T00:00:00.000Z'),
//                 maintenanceHistory: [], // attention à ne pas créer de boucle infinie ici
//                 createdAt: new Date('2022-09-18T11:25:00.000Z'),
//                 updatedAt: new Date('2023-08-20T14:15:00.000Z'),
//                 barcode: 'EQ-CBL-001',
//                 qrCode: 'https://qr.smartop360.com/equipment/equipment8',
//                 documents: []
//               },
//               parts: [], // ou liste de pièces [{ id: 'part1', name: 'Pompe hydraulique', quantity: 1 }]
//               documents: [] // ou liste de documents [{ id: 'doc1', name: 'Rapport', url: '...' }]
//             }
//           ],
          
//         createdAt: new Date('2022-09-18T11:25:00.000Z'),
//         updatedAt: new Date('2023-08-20T14:15:00.000Z'),
//         barcode: 'EQ-CBL-001',
//         qrCode: 'https://qr.smartop360.com/equipment/equipment8',
//         documents: []
//       }
      


     
//   ];
  
//   export const inventoryItems: InventoryItem[] = [
//     {
//       id: 'invitem1',
//       name: 'Câble électrique 4x10mm²',
//       SKU: 'CBL-4X10-CU',
//       category: 'Câbles électriques',
//       description: 'Câble électrique cuivre 4 conducteurs 10mm²',
//       quantity: 2500,
//       unit: 'm',
//       minimumStock: 500,
//       locationId: inventoryLocations.mainWarehouse.id,
//       supplierId: 'provider1',
//       purchasePrice: 3500,
//       currency: 'XOF',
//       purchaseDate: new Date('2023-04-15'),
//       specifications: {
//         type: 'U-1000 R2V',
//         conducteurs: '4',
//         section: '10mm²',
//         isolation: 'PVC',
//         tension: '0.6/1kV'
//       },
//       tags: ['câble', 'cuivre', '10mm²'],
//       status: InventoryItemStatus.IN_STOCK,
//       imageUrl: '/img/inventory/cable-4x10.jpg',
//       barcode: 'INV-CBL-001',
//       createdAt: new Date('2023-04-15T09:30:00Z'),
//       updatedAt: new Date('2023-08-10T14:15:00Z'),
//       transactions: [],
//       maintenanceRecords: []
//     },
//     {
//       id: 'invitem2',
//       name: 'Disjoncteur 3P+N 32A',
//       SKU: 'DJC-3PN-32A',
//       category: 'Protection électrique',
//       description: 'Disjoncteur magnétothermique 3 pôles + neutre 32A courbe C',
//       quantity: 85,
//       unit: 'pièce',
//       minimumStock: 20,
//       locationId: inventoryLocations.mainWarehouse.id,
//       supplierId: 'provider1',
//       purchasePrice: 12000,
//       currency: 'XOF',
//       purchaseDate: new Date('2023-03-22'),
//       specifications: {
//         type: 'Magnétothermique',
//         pôles: '3P+N',
//         intensité: '32A',
//         courbe: 'C',
//         'pouvoir coupure': '6kA',
//         norme: 'IEC 60898'
//       },
//       tags: ['disjoncteur', '32A', 'protection'],
//       status: InventoryItemStatus.IN_STOCK,
//       imageUrl: '/img/inventory/disj-3pn-32a.jpg',
//       barcode: 'INV-DJC-001',
//       createdAt: new Date('2023-03-22T11:45:00Z'),
//       updatedAt: new Date('2023-07-18T16:30:00Z'),
//       transactions: [],
//       maintenanceRecords: []
//     },
//     {
//       id: 'invitem3',
//       name: 'Panneau solaire 390W',
//       SKU: 'PAN-SOL-390W',
//       category: 'Énergie solaire',
//       description: 'Panneau solaire monocristallin 390W haute efficacité',
//       quantity: 42,
//       unit: 'pièce',
//       minimumStock: 10,
//       locationId: inventoryLocations.secondaryWarehouse.id,
//       supplierId: 'provider2',
//       purchasePrice: 180000,
//       currency: 'XOF',
//       purchaseDate: new Date('2023-05-05'),
//       specifications: {
//         puissance: '390W',
//         type: 'Monocristallin',
//         efficacité: '21.3%',
//         'tension Vmp': '40.5V',
//         'courant Imp': '9.63A',
//         dimensions: '1755x1038x35mm'
//       },
//       tags: ['solaire', 'panneau', '390W'],
//       status: InventoryItemStatus.IN_STOCK,
//       imageUrl: '/img/inventory/panneau-sol-390w.jpg',
//       barcode: 'INV-SOL-001',
//       createdAt: new Date('2023-05-05T13:20:00Z'),
//       updatedAt: new Date('2023-08-02T10:45:00Z'),
//       transactions: [],
//       maintenanceRecords: []
//     },
//     {
//       id: 'invitem4',
//       name: 'Connecteurs MC4',
//       SKU: 'CON-MC4-1000',
//       category: 'Accessoires solaires',
//       description: 'Paires de connecteurs MC4 pour câblage panneaux solaires',
//       quantity: 320,
//       unit: 'paire',
//       minimumStock: 50,
//       locationId: inventoryLocations.secondaryWarehouse.id,
//       supplierId: 'provider2',
//       purchasePrice: 1200,
//       currency: 'XOF',
//       purchaseDate: new Date('2023-05-10'),
//       specifications: {
//         type: 'MC4',
//         'courant max': '30A',
//         'tension max': '1000V DC',
//         'section câble': '2.5-6mm²',
//         'indice protection': 'IP67'
//       },
//       tags: ['connecteur', 'MC4', 'solaire'],
//       status: InventoryItemStatus.IN_STOCK,
//       imageUrl: '/img/inventory/connecteur-mc4.jpg',
//       barcode: 'INV-MC4-001',
//       createdAt: new Date('2023-05-10T14:50:00Z'),
//       updatedAt: new Date('2023-07-25T11:30:00Z'),
//       transactions: [],
//       maintenanceRecords: []
//     },
//     {
//       id: 'invitem5',
//       name: 'Gaine thermorétractable 20mm',
//       SKU: 'GNT-THRM-20',
//       category: 'Consommables électriques',
//       description: 'Gaine thermorétractable 20mm noir',
//       quantity: 1200,
//       unit: 'm',
//       minimumStock: 300,
//       locationId: inventoryLocations.mainWarehouse.id,
//       supplierId: 'provider1',
//       purchasePrice: 800,
//       currency: 'XOF',
//       purchaseDate: new Date('2023-02-15'),
//       specifications: {
//         diamètre: '20mm',
//         'rapport rétreint': '2:1',
//         couleur: 'Noir',
//         matériau: 'Polyoléfine',
//         'température utilisation': '-55°C à +125°C'
//       },
//       tags: ['gaine', 'thermorétractable', 'isolation'],
//       status: InventoryItemStatus.LOW_STOCK,
//       imageUrl: '/img/inventory/gaine-thermo.jpg',
//       barcode: 'INV-GTH-001',
//       createdAt: new Date('2023-02-15T16:15:00Z'),
//       updatedAt: new Date('2023-08-12T09:40:00Z'),
//       transactions: [],
//       maintenanceRecords: []
//     },
//     {
//       id: 'invitem6',
//       name: 'Onduleur 5kW triphasé',
//       SKU: 'OND-5KW-3P',
//       category: 'Conversion énergie',
//       description: 'Onduleur solaire triphasé 5kW avec monitoring',
//       quantity: 8,
//       unit: 'pièce',
//       minimumStock: 3,
//       locationId: inventoryLocations.secondaryWarehouse.id,
//       supplierId: 'provider2',
//       purchasePrice: 1200000,
//       currency: 'XOF',
//       purchaseDate: new Date('2023-06-10'),
//       specifications: {
//         puissance: '5kW',
//         'entrée DC max': '800V',
//         'sortie AC': '400V triphasé',
//         rendement: '98.2%',
//         MPPT: '2',
//         communication: 'Wi-Fi/Ethernet'
//       },
//       tags: ['onduleur', 'solaire', 'triphasé'],
//       status: InventoryItemStatus.IN_STOCK,
//       imageUrl: '/img/inventory/onduleur-5kw-3p.jpg',
//       barcode: 'INV-OND-001',
//       createdAt: new Date('2023-06-10T10:30:00Z'),
//       updatedAt: new Date('2023-08-05T15:20:00Z'),
//       transactions: [],
//       maintenanceRecords: []
//     },
//     {
//       id: 'invitem7',
//       name: 'Batterie Lithium 48V 100Ah',
//       SKU: 'BAT-LI-48-100',
//       category: 'Stockage énergie',
//       description: 'Batterie Lithium-Ion 48V 100Ah pour stockage énergie solaire',
//       quantity: 12,
//       unit: 'pièce',
//       minimumStock: 2,
//       locationId: inventoryLocations.secondaryWarehouse.id,
//       supplierId: 'provider2',
//       purchasePrice: 2500000,
//       currency: 'XOF',
//       purchaseDate: new Date('2023-07-01'),
//       specifications: {
//         technologie: 'Lithium-Ion',
//         tension: '48V',
//         capacité: '100Ah',
//         cycles: '2000+',
//         poids: '12kg'
//       },
//       tags: ['batterie', 'lithium', 'stockage'],
//       status: InventoryItemStatus.IN_STOCK,
//       imageUrl: '/img/inventory/batterie-lithium-48v.jpg',
//       barcode: 'INV-BAT-001',
//       createdAt: new Date('2023-07-01T09:10:00Z'),
//       updatedAt: new Date('2023-08-15T13:50:00Z'),
//       transactions: [],
//       maintenanceRecords: []
//     },
//     {
//       id: 'invitem8',
//       name: 'Câble solaire 6mm²',
//       SKU: 'CBL-SOL-6MM',
//       category: 'Câbles électriques',
//       description: 'Câble solaire 6mm² double isolation UV',
//       quantity: 3500,
//       unit: 'm',
//       minimumStock: 700,
//       locationId: inventoryLocations.mainWarehouse.id,
//       supplierId: 'provider1',
//       purchasePrice: 2200,
//       currency: 'XOF',
//       purchaseDate: new Date('2023-04-25'),
//       specifications: {
//         type: 'H1Z2Z2-K',
//         section: '6mm²',
//         isolation: 'Double UV',
//         tension: '1000V DC'
//       },
//       tags: ['câble', 'solaire', '6mm²'],
//       status: InventoryItemStatus.IN_STOCK,
//       imageUrl: '/img/inventory/cable-solaire-6mm.jpg',
//       barcode: 'INV-CBL-002',
//       createdAt: new Date('2023-04-25T10:30:00Z'),
//       updatedAt: new Date('2023-08-10T14:00:00Z'),
//       transactions: [],
//       maintenanceRecords: []
//     },
//     {
//       id: 'invitem9',
//       name: 'Sectionneur DC 1500V',
//       SKU: 'SEC-DC-1500V',
//       category: 'Protection électrique',
//       description: 'Sectionneur DC haute tension 1500V pour panneaux solaires',
//       quantity: 20,
//       unit: 'pièce',
//       minimumStock: 5,
//       locationId: inventoryLocations.secondaryWarehouse.id,
//       supplierId: 'provider2',
//       purchasePrice: 48000,
//       currency: 'XOF',
//       purchaseDate: new Date('2023-05-15'),
//       specifications: {
//         tension: '1500V DC',
//         courant: '32A',
//         norme: 'IEC 60947-3',
//         type: 'Sectionneur manuel'
//       },
//       tags: ['sectionneur', 'DC', 'protection'],
//       status: InventoryItemStatus.IN_STOCK,
//       imageUrl: '/img/inventory/sectionneur-dc.jpg',
//       barcode: 'INV-SEC-001',
//       createdAt: new Date('2023-05-15T11:00:00Z'),
//       updatedAt: new Date('2023-07-30T12:30:00Z'),
//       transactions: [],
//       maintenanceRecords: []
//     },
//     {
//       id: 'invitem10',
//       name: 'Câble d\'alimentation 3x2.5mm²',
//       SKU: 'CBL-3X2.5',
//       category: 'Câbles électriques',
//       description: 'Câble électrique 3 conducteurs 2.5mm²',
//       quantity: 5000,
//       unit: 'm',
//       minimumStock: 800,
//       locationId: inventoryLocations.mainWarehouse.id,
//       supplierId: 'provider1',
//       purchasePrice: 1800,
//       currency: 'XOF',
//       purchaseDate: new Date('2023-03-10'),
//       specifications: {
//         type: 'U-1000 R2V',
//         conducteurs: '3',
//         section: '2.5mm²',
//         isolation: 'PVC',
//         tension: '0.6/1kV'
//       },
//       tags: ['câble', 'cuivre', '2.5mm²'],
//       status: InventoryItemStatus.IN_STOCK,
//       imageUrl: '/img/inventory/cable-3x2.5.jpg',
//       barcode: 'INV-CBL-003',
//       createdAt: new Date('2023-03-10T08:00:00Z'),
//       updatedAt: new Date('2023-08-01T09:00:00Z'),
//       transactions: [],
//       maintenanceRecords: []
//     }
//   ];
  
  
//   export const inventoryTransactions: InventoryTransaction[] = [
//     {
//       id: 'trans1',
//       transactionType: InventoryTransactionType.RECEIPT,
//       quantity: 2500,
//       date: new Date('2023-04-15T09:30:00.000Z'),
//       reason: 'Approvisionnement initial',
//       project: undefined,
//       task: undefined,
//       notes: 'Livraison complète conforme à la commande',
//       createdAt: new Date('2023-04-15T09:30:00.000Z'),
  
//       // relations
//       itemId: 'invitem1',
//       item: inventoryItems.find(i => i.id === 'invitem1')!,
//       userId: users[0].id,
//       user: users[0],
//       fromLocationId: undefined,
//       fromLocation: undefined,
//       toLocationId: inventoryLocations.mainWarehouse.id,
//       toLocation: inventoryLocations.mainWarehouse,
//       documents: []
//     },
//     {
//       id: 'trans2',
//       transactionType: InventoryTransactionType.RECEIPT,
//       quantity: 100,
//       date: new Date('2023-03-22T11:45:00.000Z'),
//       reason: 'Approvisionnement initial',
//       project: undefined,
//       task: undefined,
//       notes: 'Livraison conforme',
//       createdAt: new Date('2023-03-22T11:45:00.000Z'),
  
//       itemId: 'invitem2',
//       item: inventoryItems.find(i => i.id === 'invitem2')!,
//       userId: users[0].id,
//       user: users[0],
//       fromLocationId: undefined,
//       fromLocation: undefined,
//       toLocationId: inventoryLocations.mainWarehouse.id,
//       toLocation: inventoryLocations.mainWarehouse,
//       documents: []
//     },
//     {
//       id: 'trans3',
//       transactionType: InventoryTransactionType.ISSUE,
//       quantity: 15,
//       date: new Date('2023-07-18T16:30:00.000Z'),
//       reason: 'Utilisation projet',
//       project: 'project1',
//       task: undefined,
//       notes: 'Utilisé pour installation tableau électrique village Diofior',
//       createdAt: new Date('2023-07-18T16:30:00.000Z'),
  
//       itemId: 'invitem2',
//       item: inventoryItems.find(i => i.id === 'invitem2')!,
//       userId: users[3].id,
//       user: users[3],
//       fromLocationId: inventoryLocations.mainWarehouse.id,
//       fromLocation: inventoryLocations.mainWarehouse,
//       toLocationId: undefined,
//       toLocation: undefined,
//       documents: []
//     },
//     {
//       id: 'trans4',
//       transactionType: InventoryTransactionType.RECEIPT,
//       quantity: 50,
//       date: new Date('2023-05-05T13:20:00.000Z'),
//       reason: 'Approvisionnement projet',
//       project: 'project2',
//       task: undefined,
//       notes: 'Livraison partielle, reste à livrer dans 2 semaines',
//       createdAt: new Date('2023-05-05T13:20:00.000Z'),
  
//       itemId: 'invitem3',
//       item: inventoryItems.find(i => i.id === 'invitem3')!,
//       userId: users[1].id,
//       user: users[1],
//       fromLocationId: undefined,
//       fromLocation: undefined,
//       toLocationId: inventoryLocations.secondaryWarehouse.id,
//       toLocation: inventoryLocations.secondaryWarehouse,
//       documents: []
//     },
//     {
//       id: 'trans5',
//       transactionType: InventoryTransactionType.ISSUE,
//       quantity: 8,
//       date: new Date('2023-08-02T10:45:00.000Z'),
//       reason: 'Installation',
//       project: 'project2',
//       task: 'task10',
//       notes: 'Installation école de Diofior',
//       createdAt: new Date('2023-08-02T10:45:00.000Z'),
  
//       itemId: 'invitem3',
//       item: inventoryItems.find(i => i.id === 'invitem3')!,
//       userId: users[2].id,
//       user: users[2],
//       fromLocationId: inventoryLocations.secondaryWarehouse.id,
//       fromLocation: inventoryLocations.secondaryWarehouse,
//       toLocationId: undefined,
//       toLocation: undefined,
//       documents: []
//     },
//     {
//       id: 'trans6',
//       transactionType: InventoryTransactionType.RECEIPT,
//       quantity: 400,
//       date: new Date('2023-05-10T14:50:00.000Z'),
//       reason: 'Approvisionnement',
//       project: undefined,
//       task: undefined,
//       notes: 'Réception conforme',
//       createdAt: new Date('2023-05-10T14:50:00.000Z'),
  
//       itemId: 'invitem4',
//       item: inventoryItems.find(i => i.id === 'invitem3')!,
//       userId: users[1].id,
//       user: users[1],
//       fromLocationId: undefined,
//       fromLocation: undefined,
//       toLocationId: inventoryLocations.secondaryWarehouse.id,
//       toLocation: inventoryLocations.secondaryWarehouse,
//       documents: []
//     },
//     {
//       id: 'trans7',
//       transactionType: InventoryTransactionType.ISSUE,
//       quantity: 80,
//       date: new Date('2023-07-25T11:30:00.000Z'),
//       reason: 'Installation',
//       project: 'project2',
//       task: 'task10',
//       notes: 'Connexion panneaux solaires',
//       createdAt: new Date('2023-07-25T11:30:00.000Z'),
  
//       itemId: 'invitem4',
//       item: inventoryItems.find(i => i.id === 'invitem4')!,
//       userId: users[2].id,
//       user: users[2],
//       fromLocationId: inventoryLocations.secondaryWarehouse.id,
//       fromLocation: inventoryLocations.secondaryWarehouse,
//       toLocationId: undefined,
//       toLocation: undefined,
//       documents: []
//     },
//     {
//       id: 'trans8',
//       transactionType: InventoryTransactionType.RECEIPT,
//       quantity: 2000,
//       date: new Date('2023-02-15T16:15:00.000Z'),
//       reason: 'Approvisionnement',
//       project: undefined,
//       task: undefined,
//       notes: 'Stock consommables',
//       createdAt: new Date('2023-02-15T16:15:00.000Z'),
  
//       itemId: 'invitem5',
//       item: inventoryItems.find(i => i.id === 'invitem5')!,
//       userId: users[0].id,
//       user: users[0],
//       fromLocationId: undefined,
//       fromLocation: undefined,
//       toLocationId: inventoryLocations.mainWarehouse.id,
//       toLocation: inventoryLocations.mainWarehouse,
//       documents: []
//     },
//     {
//       id: 'trans9',
//       transactionType: InventoryTransactionType.ISSUE,
//       quantity: 800,
//       date: new Date('2023-08-12T09:40:00.000Z'),
//       reason: 'Consommation',
//       project: 'project1',
//       task: undefined,
//       notes: "Utilisé pour travaux d'isolation",
//       createdAt: new Date('2023-08-12T09:40:00.000Z'),
  
//       itemId: 'invitem5',
//       item: inventoryItems.find(i => i.id === 'invitem5')!,
//       userId: users[3].id,
//       user: users[3],
//       fromLocationId: inventoryLocations.mainWarehouse.id,
//       fromLocation: inventoryLocations.mainWarehouse,
//       toLocationId: undefined,
//       toLocation: undefined,
//       documents: []
//     },
//     {
//       id: 'trans10',
//       transactionType: InventoryTransactionType.RECEIPT,
//       quantity: 12,
//       date: new Date('2023-06-15T11:45:00.000Z'),
//       reason: 'Approvisionnement projet',
//       project: 'project2',
//       task: undefined,
//       notes: 'Batteries pour stockage énergie solaire',
//       createdAt: new Date('2023-06-15T11:45:00.000Z'),
  
//       itemId: 'invitem7',
//       item: inventoryItems.find(i => i.id === 'invitem7')!,
//       userId: users[1].id,
//       user: users[1],
//       fromLocationId: undefined,
//       fromLocation: undefined,
//       toLocationId: inventoryLocations.secondaryWarehouse.id,
//       toLocation: inventoryLocations.secondaryWarehouse,
//       documents: []
//     },
//     {
//       id: 'trans11',
//       transactionType: InventoryTransactionType.TRANSFER,
//       quantity: 5,
//       date: new Date('2023-07-20T13:15:00.000Z'),
//       reason: 'Transfert vers site projet',
//       project: 'project1',
//       task: undefined,
//       notes: 'Coffrets nécessaires pour installation site Fatick',
//       createdAt: new Date('2023-07-20T13:15:00.000Z'),
  
//       itemId: 'invitem8',
//       item: inventoryItems.find(i => i.id === 'invitem8')!,
//       userId: users[2].id,
//       user: users[2],
//       fromLocationId: inventoryLocations.mainWarehouse.id,
//       fromLocation: inventoryLocations.mainWarehouse,
//       toLocationId: inventoryLocations.fatickSite.id,
//       toLocation: inventoryLocations.fatickSite,
//       documents: []
//     },
//     {
//       id: 'trans12',
//       transactionType: InventoryTransactionType.RECEIPT,
//       quantity: 30,
//       date: new Date('2023-03-20T15:50:00.000Z'),
//       reason: 'Approvisionnement',
//       project: undefined,
//       task: undefined,
//       notes: 'Réception conforme',
//       createdAt: new Date('2023-03-20T15:50:00.000Z'),
  
//       itemId: 'invitem9',
//       item: inventoryItems.find(i => i.id === 'invitem9')!,
//       userId: users[0].id,
//       user: users[0],
//       fromLocationId: undefined,
//       fromLocation: undefined,
//       toLocationId: inventoryLocations.mainWarehouse.id,
//       toLocation: inventoryLocations.mainWarehouse,
//       documents: []
//     },
//     {
//       id: 'trans13',
//       transactionType: InventoryTransactionType.ISSUE,
//       quantity: 15,
//       date: new Date('2023-08-15T10:15:00.000Z'),
//       reason: 'Installation',
//       project: 'project1',
//       task: 'task2',
//       notes: 'Installation tableaux électriques',
//       createdAt: new Date('2023-08-15T10:15:00.000Z'),
  
//       itemId: 'invitem9',
//       item: inventoryItems.find(i => i.id === 'invitem9')!,
//       userId: users[3].id,
//       user: users[3],
//       fromLocationId: inventoryLocations.mainWarehouse.id,
//       fromLocation: inventoryLocations.mainWarehouse,
//       toLocationId: undefined,
//       toLocation: undefined,
//       documents: []
//     },
//     {
//       id: 'trans14',
//       transactionType: InventoryTransactionType.TRANSFER,
//       quantity: 500,
//       date: new Date('2023-07-10T14:30:00.000Z'),
//       reason: 'Transfert matériel',
//       project: 'project1',
//       task: undefined,
//       notes: 'Câble pour tirage réseau village Diofior',
//       createdAt: new Date('2023-07-10T14:30:00.000Z'),
  
//       itemId: 'invitem1',
//       item: inventoryItems.find(i => i.id === 'invitem1')!,
//       userId: users[2].id,
//       user: users[2],
//       fromLocationId: inventoryLocations.mainWarehouse.id,
//       fromLocation: inventoryLocations.mainWarehouse,
//       toLocationId: inventoryLocations.fatickSite.id,
//       toLocation: inventoryLocations.fatickSite,
//       documents: []
//     },
//     {
//       id: 'trans15',
//       transactionType: InventoryTransactionType.COUNT,
//       quantity: 1200,
//       date: new Date('2023-08-01T09:00:00.000Z'),
//       reason: 'Inventaire mensuel',
//       project: undefined,
//       task: undefined,
//       notes: 'Vérification stock gaine thermorétractable',
//       createdAt: new Date('2023-08-01T09:00:00.000Z'),
  
//       itemId: 'invitem5',
//       item: inventoryItems.find(i => i.id === 'invitem5')!,
//       userId: users[0].id,
//       user: users[0],
//       fromLocationId: inventoryLocations.mainWarehouse.id,
//       fromLocation: inventoryLocations.mainWarehouse,
//       toLocationId: undefined,
//       toLocation: undefined,
//       documents: []
//     }
//   ];
  
//   export const maintenanceRecords: MaintenanceRecord[] = [
//     // --- Record original corrigé ---
//     {
//       id: 'mr1',
//       maintenanceType: MaintenanceType.PREVENTIVE,
//       date: new Date('2023-07-20T08:00:00.000Z'),
//       description: 'Vérification du groupe électrogène',
//       cost: 150000,
//       currency: 'XOF',
//       status: MaintenanceStatus.COMPLETED,
//       notes: 'Filtre et huile changés',
//       scheduledDate: new Date('2023-07-15T00:00:00.000Z'),
//       completedDate: new Date('2023-07-20T12:00:00.000Z'),
//       createdAt: new Date('2023-07-15T09:00:00.000Z'),
//       updatedAt: new Date('2023-07-20T12:00:00.000Z'),
  
//       equipmentId: equipments[0].id,
//       equipment: equipments[0],
//       technicianId: users[2].id,
//       technician: users[2],
//       createdById: users[0].id,
//       createdBy: users[0],
//       parts: [ inventoryItems[0] ],  // inventoryItems[0] doit contenir tous les champs
//       documents: []
//     },
  
//     // --- maint3 corrigé ---
//     {
//       id: 'maint3',
//       maintenanceType: MaintenanceType.PREVENTIVE,
//       date: new Date('2023-05-05T00:00:00.000Z'),
//       description: 'Maintenance périodique du groupe électrogène',
//       cost: 120000,
//       currency: 'XOF',
//       status: MaintenanceStatus.COMPLETED,
//       notes: 'Changement filtres et huile, vérification générale',
//       scheduledDate: new Date('2023-05-05T00:00:00.000Z'),
//       completedDate: new Date('2023-05-05T00:00:00.000Z'),
//       createdAt: new Date('2023-04-20T15:45:00.000Z'),
//       updatedAt: new Date('2023-05-05T10:30:00.000Z'),
  
//       equipmentId: 'equipment4',
//       equipment: {
//         id: 'equipment4',
//         name: 'Groupe électrogène GE-500',
//         type: 'Groupe électrogène',
//         model: 'GE-500',
//         serialNumber: 'GEN-2021-001',
//         manufacturer: 'PowerGen',
//         purchaseDate: new Date('2021-06-01T00:00:00.000Z'),
//         purchasePrice: 8000000,
//         currency: 'XOF',
//         warrantyExpirationDate: new Date('2023-06-01T00:00:00.000Z'),
//         status: EquipmentStatus.AVAILABLE,
//         condition: EquipmentCondition.GOOD,
//         description: '',
//         specifications: {},
//         category: EquipmentCategory.POWER,
//         tags: [],
//         createdAt: new Date(),
//         updatedAt: new Date(),
//         maintenanceHistory: [],
//         documents: []
//       },
//       technicianId: users[3].id,
//       technician: users[3],
//       createdById: users[2].id,
//       createdBy: users[2],
//       parts: [
     
//       ]
//       ,
//       documents: []
//     },
  
//     // --- maint4 corrigé ---
//     {
//       id: 'maint4',
//       maintenanceType: MaintenanceType.CALIBRATION,
//       date: new Date('2023-07-10T00:00:00.000Z'),
//       description: 'Calibration du testeur haute tension',
//       cost: 45000,
//       currency: 'XOF',
//       status: MaintenanceStatus.COMPLETED,
//       notes: 'Calibration selon procédure standard, certificat émis',
//       scheduledDate: new Date('2023-07-10T00:00:00.000Z'),
//       completedDate: new Date('2023-07-10T00:00:00.000Z'),
//       createdAt: new Date('2023-06-25T11:30:00.000Z'),
//       updatedAt: new Date('2023-07-10T16:45:00.000Z'),
  
//       equipmentId: 'equipment3',
//       equipment: equipments.find(e => e.id === 'equipment3')!,
//       technicianId: users[3].id,
//       technician: users[3],
//       createdById: users[1].id,
//       createdBy: users[1],
//       parts: [],
//       documents: []
//     },
  
//     // --- maint5 corrigé ---
//     {
//       id: 'maint5',
//       maintenanceType: MaintenanceType.PREVENTIVE,
//       date: new Date('2023-06-20T00:00:00.000Z'),
//       description: 'Entretien du poste à souder',
//       cost: 35000,
//       currency: 'XOF',
//       status: MaintenanceStatus.COMPLETED,
//       notes: 'Nettoyage, vérification des connexions, test de fonctionnement',
//       scheduledDate: new Date('2023-06-20T00:00:00.000Z'),
//       completedDate: new Date('2023-06-20T00:00:00.000Z'),
//       createdAt: new Date('2023-06-05T09:15:00.000Z'),
//       updatedAt: new Date('2023-06-20T11:15:00.000Z'),
  
//       equipmentId: 'equipment6',
//       equipment: equipments.find(e => e.id === 'equipment6')!,
//       technicianId: users[3].id,
//       technician: users[3],
//       createdById: users[2].id,
//       createdBy: users[2],
//       parts: [],
//       documents: []
//     },
  
//     // --- maint6 corrigé (tech externe complet) ---
//     {
//       id: 'maint6',
//       maintenanceType: MaintenanceType.CALIBRATION,
//       date: new Date('2023-07-05T00:00:00.000Z'),
//       description: 'Calibration du GPS haute précision',
//       cost: 65000,
//       currency: 'XOF',
//       status: MaintenanceStatus.COMPLETED,
//       notes: 'Calibration effectuée par technicien du fabricant',
//       scheduledDate: new Date('2023-07-05T00:00:00.000Z'),
//       completedDate: new Date('2023-07-05T00:00:00.000Z'),
//       createdAt: new Date('2023-06-20T14:20:00.000Z'),
//       updatedAt: new Date('2023-07-05T16:20:00.000Z'),
    
//       equipmentId: 'equipment9',
//       equipment: equipments.find(e => e.id === 'equipment9')!,
//       technicianId: 'ext-tech1',
//       technician: {
//         id: 'ext-tech1',
//         name: 'Technicien TerraNav',
//         email: 'service@terranav.com',
//         password: "kkkkkkkkkkkkkkk",
//         role: UserRole.CONTRACTOR,
//         status: UserStatus.ACTIVE,
//         createdAt: new Date(),
//         updatedAt: new Date()
//       },
//       createdById: users[1].id,
//       createdBy: users[1],
//       parts: [],
//       documents: []
//     },
  
//     // --- maint7 corrigé ---
//     {
//       id: 'maint7',
//       maintenanceType: MaintenanceType.CORRECTIVE,
//       date: new Date('2023-06-15T00:00:00.000Z'),
//       description: 'Réparation du système hydraulique de la nacelle',
//       cost: 180000,
//       currency: 'XOF',
//       status: MaintenanceStatus.COMPLETED,
//       notes: 'Pièces remplacées et test de validation',
//       scheduledDate: new Date('2023-06-15T00:00:00.000Z'),
//       completedDate: new Date('2023-06-15T00:00:00.000Z'),
//       createdAt: new Date(),
//       updatedAt: new Date(),
  
//       equipmentId: 'equipment2',
//       equipment: equipments.find(e => e.id === 'equipment2')!,
//       technicianId: users[3].id,
//       technician: users[3],
//       createdById: users[3].id,
//       createdBy: users[3],
//       parts: [],
//       documents: []
//     }
//   ];

 
//   // Export all inventory-related data
//   export default {
//     inventoryLocations,
//     equipments,
//     inventoryItems,
//     inventoryTransactions,
//     maintenanceRecords
//   };
  